--- 
$schemaver: 1.1
name: aws-codepipeline-lambda-slack-webhook
type: Web Service
aliases:
short_description: Lambda for generic slack webhook
assignment_group: gro:AD-Student Life Applications
notes: 
maintained_by:
  - eric-nord
developed_by_byu: True
ddd:
  business_domain: 
  ubiquitous_language_url: 
  context_map_url: 
links:
  system_documentation_url: https://github.com/byu-oit/aws-codepipeline-lambda-slack-webhook
  source_repo_url: https://github.com/byu-oit/aws-codepipeline-lambda-slack-webhook
  swagger_urls:
microservice: False
technologies_used:
  - Python
stages:
  production:
    urls:
      product_page: https://github.com/byu-oit/aws-codepipeline-lambda-slack-webhook
      physical_url: 
      virtual_url: 
    hosting_location: 
    aws_account: 
    relationships: 
      depends_on:
        db_read_write:
        db_read_only:
        software:
      supports:
        software:
        service:
      reverse_proxy: 
      runs_on:
        server_cluster:
        virtual_server:
        rack_server:
        blade_server:
tags:
  data-sensitivity: confidential
  env: prd
  app: aws-codepipeline-lambda-slack-webhook
  team: gro:AD-Student Life Applications
federation_json_url: https://raw.githubusercontent.com/byu-oit/aws-codepipeline-lambda-slack-webhook/master/.repo-meta.yml

