version: 0.1
phases:
  install:
    commands:
      - echo no os dependencies required
  pre_build:
    commands:
      - echo Installing requirements from requirements.txt
      - pip install -r requirements.txt -t .
  build:
    commands:
      - aws s3 cp s3://byu-427927161742-us-west-2-cloudformation-templates/iac/cloudformation/lambda/lambda-cf.yaml .
      - aws cloudformation package --template-file lambda-cf.yaml --s3-bucket byu-035170473189-us-west-2-code-build-artifacts --output-template-file sam_post.yaml
      - echo $?
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - sam_post.yaml
    - cfg-dev.json
    - cfg-stg.json
    - cfg-prd.json
