AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: Generic lamda template

Parameters: 
  team:
    Type: String
    Description: (required) team name - lookup @ https://home.byu.edu/webapp/grouss-web/userSynchronizationSummary.htm
  env:
    Type: String
    Description:  (required) see - https://byuoit.atlassian.net/wiki/display/OAPP/Tagging
    AllowedValues:
      - dev
      - dev-noshutdown
      - test
      - stage
      - prod
  dataSensitivity:
    Type: String
    Description: (required) - see https://byuoit.atlassian.net/wiki/display/OAPP/Tagging
    AllowedValues:
      - public
      - internal
      - confidential
      - highly confidential
  app:
    Type: String
    Description: (required) Application name (Also used for bucket name. Follow S3 bucket name conventions)
  runtime:
    Type: String
    Description: Lambda runtime
    #Verify values based on cfn error response when trying invalid value Q12017
    AllowedValues:
      - java8
      - nodejs
      - nodejs4.3
      - python2.7
  handler:
    Type: String
    Description: >-
      The filename.handler-method value in your function. 
      For example, "main.handler" would call the handler method defined in main.py.
  timeout:
    Type: String
    Description: Lambda timeout in minutes
    Default: 3
  lambdaMemory:
    Type: "Number"
    Description: "The ammount of Memory to allocate for the Lambda"
    Default: 128
    AllowedValues:
      - 128
      - 192
      - 256
      - 320
      - 384
      - 448
      - 512
      - 576
      - 640
      - 704
      - 768
      - 832
      - 896
      - 960
      - 1024
      - 1088
      - 1152
      - 1216
      - 1280
      - 1344
      - 1408
      - 1472
      - 1536

  #Conditional flags
  createBucket:
    Type: String
    Description: Would you like fries... I mean... an S3 bucket with your order
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
  
Resources:
  # Required Roles and policies
  LambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref app
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "s3.amazonaws.com"
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: S3Put
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: s3:PutObject
                Resource: "*"

  # Lambda creation
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: !Ref handler
      Runtime: !Ref runtime
      #CodeUri is overwritten by "aws cloudformation package" command
      CodeUri: .
      MemorySize: !Ref lambdaMemory
      Timeout: !Ref timeout
      Role: !GetAtt EventListRole.Arn
Outputs:
  lambdaArn:
    Value: !GetAtt EventListFunction.Arn